import assert from 'node:assert/strict';
import prisma from '../utils/db';
import bcrypt from 'bcryptjs';
import { trustedSecurityMobile } from '../utils/security-mobile';
let actor: any;
const authPath = require.resolve('../utils/auth');
require.cache[authPath] = { id: authPath, filename: authPath, loaded: true, exports: { auth: { api: { getSession: async () => actor ? { user: actor } : null } } } } as NodeModule;
require('../utils/persistent-rate-limit').consumePersistentRateLimit = async () => ({ allowed: true });
const codes: string[] = [];
require('../utils/sms').getSmsSender = () => ({ sendSms: async (_phone: string, message: string) => { codes.push(message.match(/\b\d{6}\b/)![0]); return { success: true }; } });
const router = require('./account-contact').default;
const db = prisma as any;
let hash: string;
let record: any;
let phone = '9812345678';
let revoked = false;
let securityMobile: string | null = null;
let securityMobileVerifiedAt: Date | null = null;
db.user.findFirst = async () => ({ id: 'admin', phone, securityMobile, securityMobileVerifiedAt });
db.account.findFirst = async () => ({ password: hash });
db.verificationCode.create = async ({ data }: any) => (record = { id: 'challenge', consumedAt: null, attempts: 0, ...data });
db.verificationCode.findFirst = async () => record && !record.consumedAt && record.attempts < 5 && record.expiresAt > new Date() ? { ...record } : null;
db.verificationCode.updateMany = async ({ where, data }: any) => {
  if (!where.id) return { count: 0 };
  if (record.consumedAt || record.attempts !== where.attempts) return { count: 0 };
  if (data.consumedAt) record.consumedAt = data.consumedAt; else record.attempts++;
  return { count: 1 };
};
db.user.updateMany = async ({ where, data }: any) => { if (where.phone !== phone) return { count: 0 }; phone = data.phone; securityMobile = data.securityMobile; securityMobileVerifiedAt = data.securityMobileVerifiedAt; return { count: 1 }; };
db.session.deleteMany = async () => { revoked = true; return { count: 1 }; };
db.$transaction = async (run: any) => run(db);
async function invoke(path: string, body: any) {
  const route = router.stack.find((layer: any) => layer.route?.path === path).route;
  const req: any = { headers: {}, body }; let status = 200; let payload: any;
  const res: any = { status(value: number) { status = value; return this; }, json(value: any) { payload = value; return this; } };
  for (const layer of route.stack) { let next = false; await layer.handle(req, res, () => { next = true; }); if (!next) break; }
  return { status, payload };
}
async function main() {
  hash = await bcrypt.hash('CorrectPassword!', 4);
  const body = { password: 'CorrectPassword!', phone: '9800000000' };
  assert.equal((await invoke('/mobile/start', body)).status, 401);
  actor = { id: 'admin', tenantId: 'tenant', roles: [{ roleName: 'Branch Admin', branchId: 'branch' }] };
  assert.equal((await invoke('/mobile/start', body)).status, 403);
  actor.roles = [{ roleName: 'Tenant Admin', branchId: null }];
  assert.equal((await invoke('/mobile/start', { ...body, password: 'wrong' })).status, 403);
  process.env.SMS_PROVIDER = 'MOCK';
  assert.equal((await invoke('/mobile/start', body)).status, 503);
  process.env.SMS_PROVIDER = 'AAKASH'; process.env.AAKASH_SMS_AUTH_TOKEN = 'test-only';
  assert.equal((await invoke('/mobile/start', body)).status, 200);
  assert.equal(phone, '9812345678');
  const confirm = { challengeId: 'challenge', currentCode: codes[0], newCode: codes[1] };
  assert.equal((await invoke('/mobile/confirm', { ...confirm, newCode: 'wrong' })).status, 400);
  assert.equal((await invoke('/mobile/confirm', { ...confirm, newCode: codes[1] === '000000' ? '111111' : '000000' })).status, 400);
  assert.equal(record.attempts, 1);
  actor.tenantId = 'other'; assert.equal((await invoke('/mobile/confirm', confirm)).status, 400); actor.tenantId = 'tenant';
  assert.equal((await invoke('/mobile/confirm', confirm)).status, 200);
  assert.equal(phone, '9800000000'); assert.equal(revoked, true);
  assert.equal(trustedSecurityMobile({ phone, securityMobile, securityMobileVerifiedAt }), phone);
  assert.equal((await invoke('/mobile/confirm', confirm)).status, 400);
  securityMobile = null; securityMobileVerifiedAt = null;
  assert.equal((await invoke('/mobile', {})).payload.verified, false);
  assert.equal(trustedSecurityMobile({ phone }), null, 'Legacy saved numbers are not trusted');
  codes.length = 0;
  assert.equal((await invoke('/mobile/start', { password: 'CorrectPassword!', verifyExisting: true, phone: '9811111111' })).status, 200);
  assert.equal(codes.length, 1, 'Existing-number verification sends one code');
  assert.equal(JSON.parse(record.identifier).newPhone, phone, 'Client cannot choose bootstrap destination');
  assert.equal((await invoke('/mobile/confirm', { challengeId: 'challenge', currentCode: codes[0] })).status, 200);
  assert.equal((await invoke('/mobile', {})).payload.verified, true);
  assert.equal(trustedSecurityMobile({ phone: '9811111111', securityMobile, securityMobileVerifiedAt }), null, 'Phone edits cannot transfer trust');
  assert.equal((await invoke('/mobile/confirm', { challengeId: 'challenge', currentCode: codes[0] })).status, 400);
  codes.length = 0;
  await invoke('/mobile/start', { password: 'CorrectPassword!', verifyExisting: true });
  record.expiresAt = new Date(0);
  assert.equal((await invoke('/mobile/confirm', { challengeId: 'challenge', currentCode: codes[0] })).status, 400);
  phone = '';
  assert.equal((await invoke('/mobile/start', { password: 'CorrectPassword!', verifyExisting: true })).status, 409);
  assert.equal((await invoke('/mobile', {})).payload.recoveryRequired, true);
  console.log('PASS legacy distrust, exact destination binding, bootstrap verification, expiry, replay and recovery status');
  console.log('PASS mobile contact roles, password, delivery configuration, dual codes, tenant binding, update, session revocation, replay');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
